language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

matrix:
  allow_failures:
    - php: 5.3.3
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
    - env: DB=pgsql
    - env: DB=sqlite

script: vendor/bin/tester tests -s -c tests/php.ini

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'create database zeminem;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -D zeminem < sql/mysql.sql; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database zeminem;' -U postgres; fi"
  - composer selfupdate
  - composer install --prefer-dist --no-dev

#TODO: before_script - generovat pomoci prikazu, nepouzivat SQL dumpy (Doctrine)