language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.3.3
    - php: 5.5
    - php: hhvm

script: vendor/bin/tester tests -s -c tests/php.ini

before_script:
  - mysql -u root -e 'create database zeminem;'
  - mysql -u root -D zeminem < zeminem.sql
  - mysql -u root -D zeminem < diff.sql
  - composer selfupdate
  - composer update