language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

script: vendor/bin/tester tests -s -c tests/php.ini

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
  - mysql -u root -e 'create database zeminem;'
  - mysql -u root -D zeminem < zeminem.sql
  - mysql -u root -D zeminem < diff.sql
  - composer update